function registerStockActions_(){
  registerActionOnce_('stock.list',function(p){requireRole(getAuthContext_(),['director','manager','engineer','purchasing','warehouse','accountant']);return stockList_(p||{});},false);
  registerActionOnce_('stock.card',function(p){requireRole(getAuthContext_(),['director','manager','engineer','purchasing','warehouse','accountant']);return stockCard_(p&&p.sku);},false);
  registerActionOnce_('stock.reserve',function(p){requireRole(getAuthContext_(),['warehouse']);return reserveStock_(p);},true);
  registerActionOnce_('stock.release',function(p){requireRole(getAuthContext_(),['warehouse']);return releaseStock_(p&&p.res_id,p&&p.qty);},true);
  registerActionOnce_('stock.receive',function(p){requireRole(getAuthContext_(),['warehouse']);return receiveStock_(p);},true);
  registerActionOnce_('stock.adjust',function(p){requireRole(getAuthContext_(),['warehouse']);return adjustStock_(p);},true);
  registerActionOnce_('bom.reconcile',function(p){requireRole(getAuthContext_(),['manager','engineer','warehouse']);return reconcileBom_(p&&p.project_id);},true);
  registerActionOnce_('issue.create',function(p){requireRole(getAuthContext_(),['warehouse']);return createIssue_(p);},true);
  registerActionOnce_('issue.post',function(p){requireRole(getAuthContext_(),['warehouse']);return postIssue_(p&&p.px_id);},true);
  registerActionOnce_('issue.cancel',function(p){requireRole(getAuthContext_(),['warehouse']);return cancelIssue_(p&&p.px_id);},true);
}
function stockBalanceId_(sku,wh){return String(sku)+'@'+String(wh);}
function findBalance_(sku,wh){return query('StockBalance',function(r){return String(r.sku)===String(sku)&&String(r.wh_id)===String(wh);})[0]||null;}
function saveBalance_(sku,wh,onHand,reserved){if(onHand<0)throw apiError('STOCK_INSUFFICIENT','Tồn thực tế không đủ cho '+sku);if(reserved<0||reserved>onHand)throw apiError('STOCK_INSUFFICIENT','Tồn giữ chỗ không hợp lệ cho '+sku);var old=findBalance_(sku,wh),value={sku:sku,wh_id:wh,qty_on_hand:onHand,qty_reserved:reserved};return old?update('StockBalance',old.sku,value):insert('StockBalance',value);}
function movement_(type,p){return insert('StockMovements',{mv_id:nextId('MV'),ts:getDbTimestamp_(),type:type,sku:p.sku,wh_id:p.wh_id,qty:Number(p.qty),unit_cost_vnd:Number(p.unit_cost_vnd||0),project_id:p.project_id||'',ref_doc:p.ref_doc||'',note:p.note||''});}
function stockList_(filter){var items={},warehouses={};readAll('Items').forEach(function(i){items[String(i.sku)]=i;});readAll('Warehouses').forEach(function(w){warehouses[String(w.wh_id)]=w;});var t=String(filter.search||'').toLowerCase(),wh=String(filter.wh_id||'');return readAll('StockBalance').filter(function(r){var i=items[String(r.sku)]||{};return(!wh||String(r.wh_id)===wh)&&(!t||[r.sku,i.name,i.barcode].join(' ').toLowerCase().indexOf(t)>=0);}).map(function(r){var x=copyDbObject_(r),i=items[String(r.sku)]||{};x.name=i.name||'';x.min_stock=Number(i.min_stock||0);x.available=Number(r.qty_on_hand||0)-Number(r.qty_reserved||0);x.alert=x.available<=0&&x.min_stock>0?'out':x.available<x.min_stock?'low':'';x.warehouse_name=(warehouses[String(r.wh_id)]||{}).name||r.wh_id;x.reservations=query('StockReservations',function(z){return String(z.sku)===String(r.sku)&&String(z.wh_id)===String(r.wh_id)&&String(z.status)==='active';});return x;});}
function stockCard_(sku){if(!findById('Items',sku))throw apiError('NOT_FOUND','Không tìm thấy SKU: '+sku);return{balances:query('StockBalance',function(r){return String(r.sku)===String(sku);}),movements:query('StockMovements',function(r){return String(r.sku)===String(sku);}).sort(function(a,b){return String(b.ts).localeCompare(String(a.ts));})};}
function reserveStock_(p){var q=Number(p&&p.qty);if(!(q>0))throw apiError('VALIDATION','Số lượng giữ chỗ phải lớn hơn 0.','qty');var b=findBalance_(p.sku,p.wh_id);if(!b||Number(b.qty_on_hand)-Number(b.qty_reserved)<q)throw apiError('STOCK_INSUFFICIENT','Khả dụng không đủ cho '+p.sku);var res=insert('StockReservations',{res_id:nextId('RES'),project_id:p.project_id,sku:p.sku,wh_id:p.wh_id,qty:q,status:'active'});saveBalance_(p.sku,p.wh_id,Number(b.qty_on_hand),Number(b.qty_reserved)+q);movement_('reserve',{sku:p.sku,wh_id:p.wh_id,qty:q,project_id:p.project_id,ref_doc:res.res_id});return res;}
function releaseStock_(id,qty){var r=findById('StockReservations',id);if(!r||String(r.status)!=='active')throw apiError('NOT_FOUND','Không tìm thấy giữ chỗ đang hoạt động: '+id);var q=qty===undefined?Number(r.qty):Number(qty);if(!(q>0)||q>Number(r.qty))throw apiError('VALIDATION','Số lượng giải phóng không hợp lệ.','qty');var b=findBalance_(r.sku,r.wh_id);saveBalance_(r.sku,r.wh_id,Number(b.qty_on_hand),Number(b.qty_reserved)-q);if(q===Number(r.qty))update('StockReservations',id,{status:'released'});else update('StockReservations',id,{qty:Number(r.qty)-q});movement_('release',{sku:r.sku,wh_id:r.wh_id,qty:q,project_id:r.project_id,ref_doc:id});return{released:q};}
function receiveStock_(p){var q=Number(p&&p.qty);if(!(q>0))throw apiError('VALIDATION','Số lượng nhập phải lớn hơn 0.','qty');var b=findBalance_(p.sku,p.wh_id);saveBalance_(p.sku,p.wh_id,Number(b&&b.qty_on_hand||0)+q,Number(b&&b.qty_reserved||0));return movement_('receipt',p);}
function adjustStock_(p){var q=Number(p&&p.qty);if(!Number.isFinite(q)||q===0)throw apiError('VALIDATION','Số lượng điều chỉnh phải khác 0.','qty');var b=findBalance_(p.sku,p.wh_id);if(!b)throw apiError('NOT_FOUND','Chưa có tồn kho cho '+p.sku);saveBalance_(p.sku,p.wh_id,Number(b.qty_on_hand)+q,Number(b.qty_reserved));return movement_('adjust',p);}
function reconcileBom_(projectId){if(!findById('Projects',projectId))throw apiError('NOT_FOUND','Không tìm thấy dự án: '+projectId);var createdRes=0,createdPr=0;query('BOM',function(r){return String(r.project_id)===String(projectId);}).sort(function(a,b){return String(a.need_date).localeCompare(String(b.need_date));}).forEach(function(line){var need=Number(line.qty_required)-Number(line.qty_issued||0)-Number(line.qty_reserved||0)-Number(line.qty_ordered||0);if(need<=0)return;var balances=stockList_({}).filter(function(b){return String(b.sku)===String(line.sku)&&['common','consumable'].indexOf(String((findById('Warehouses',b.wh_id)||{}).wh_type))>=0&&b.available>0;});balances.forEach(function(b){if(need<=0)return;var take=Math.min(need,b.available);reserveStock_({project_id:projectId,sku:line.sku,wh_id:b.wh_id,qty:take});update('BOM',line.bom_id,{qty_reserved:Number(line.qty_reserved||0)+take});line.qty_reserved=Number(line.qty_reserved||0)+take;need-=take;createdRes++;});if(need>0){var pr=query('PR',function(r){return String(r.project_id)===String(projectId)&&String(r.sku)===String(line.sku)&&String(r.status)==='open';})[0];if(pr)update('PR',pr.pr_id,{qty:need,need_date:line.need_date});else{insert('PR',{pr_id:nextId('PR'),project_id:projectId,sku:line.sku,qty:need,need_date:line.need_date,status:'open',source:'bom_auto'});createdPr++;}}});return{reservations_created:createdRes,prs_created:createdPr};}
function createIssue_(p){if(!p||!p.project_id||!Array.isArray(p.lines)||!p.lines.length)throw apiError('VALIDATION','Phiếu xuất cần dự án và ít nhất một dòng.');if(!findById('Projects',p.project_id))throw apiError('NOT_FOUND','Không tìm thấy dự án: '+p.project_id);var grouped={};p.lines.forEach(function(l){if(!findById('Items',l.sku))throw apiError('NOT_FOUND','Không tìm thấy SKU: '+l.sku);if(!(Number(l.qty)>0))throw apiError('VALIDATION','Số lượng xuất phải lớn hơn 0.','qty');grouped[String(l.sku)]=(grouped[String(l.sku)]||0)+Number(l.qty);});var id=nextId('PX'),note=insert('IssueNotes',{px_id:id,project_id:p.project_id,ts:getDbTimestamp_(),status:'draft'}),skus=Object.keys(grouped);insertMany('IssueLines',skus.map(function(sku,i){return{line_id:id+'-'+(i+1),px_id:id,sku:sku,qty:grouped[sku],unit_cost_vnd:Number((findById('Items',sku)||{}).avg_cost_vnd||0)};}));return note;}
function activeReservedQty_(projectId,sku){return query('StockReservations',function(r){return String(r.project_id)===String(projectId)&&String(r.sku)===String(sku)&&String(r.status)==='active';}).reduce(function(s,r){return s+Number(r.qty||0);},0);}
function postIssue_(id){var note=findById('IssueNotes',id);if(!note)throw apiError('NOT_FOUND','Không tìm thấy phiếu xuất: '+id);if(String(note.status)!=='draft')throw apiError('INVALID_STATE','Chỉ phiếu nháp mới được xuất.');var lines=query('IssueLines',function(r){return String(r.px_id)===String(id);});lines.forEach(function(l){var item=findById('Items',l.sku)||{},allow=String((findById('Settings','allow_consumable_without_reserve')||{}).value)==='true'&&String(item.category)==='consumable',reserved=activeReservedQty_(note.project_id,l.sku);if(!allow&&reserved<=0)throw apiError('STOCK_NOT_RESERVED','Dự án '+note.project_id+' chưa giữ chỗ '+l.sku);if(!allow&&Number(l.qty)>reserved)throw apiError('STOCK_INSUFFICIENT','Dự án '+note.project_id+' chỉ đang giữ '+reserved+' '+l.sku);consumeIssueLine_(note,l,allow);});update('IssueNotes',id,{status:'posted'});return findById('IssueNotes',id);}
function consumeIssueLine_(note,line,withoutReserve){var left=Number(line.qty),reservations=query('StockReservations',function(r){return String(r.project_id)===String(note.project_id)&&String(r.sku)===String(line.sku)&&String(r.status)==='active';});if(withoutReserve){var b=readAll('StockBalance').filter(function(x){return String(x.sku)===String(line.sku)&&Number(x.qty_on_hand)-Number(x.qty_reserved)>=left;})[0];if(!b)throw apiError('STOCK_INSUFFICIENT','Tồn khả dụng không đủ cho '+line.sku);saveBalance_(b.sku,b.wh_id,Number(b.qty_on_hand)-left,Number(b.qty_reserved));movement_('issue',{sku:b.sku,wh_id:b.wh_id,qty:left,project_id:note.project_id,ref_doc:note.px_id,unit_cost_vnd:line.unit_cost_vnd,note:'unreserved'});}else reservations.forEach(function(r){if(left<=0)return;var take=Math.min(left,Number(r.qty)),b=findBalance_(r.sku,r.wh_id);saveBalance_(r.sku,r.wh_id,Number(b.qty_on_hand)-take,Number(b.qty_reserved)-take);if(take===Number(r.qty))update('StockReservations',r.res_id,{status:'consumed'});else update('StockReservations',r.res_id,{qty:Number(r.qty)-take});movement_('issue',{sku:r.sku,wh_id:r.wh_id,qty:take,project_id:note.project_id,ref_doc:note.px_id,unit_cost_vnd:line.unit_cost_vnd,note:'reserved'});left-=take;});var bom=query('BOM',function(b){return String(b.project_id)===String(note.project_id)&&String(b.sku)===String(line.sku);})[0];if(bom)update('BOM',bom.bom_id,{qty_issued:Number(bom.qty_issued||0)+Number(line.qty),qty_reserved:Math.max(0,Number(bom.qty_reserved||0)-Number(line.qty))});insert('ProjectCosts',{id:nextId('COST'),project_id:note.project_id,kind:'material',amount_vnd:Number(line.qty)*Number(line.unit_cost_vnd||0),ref_type:'issue',ref_id:note.px_id,ts:getDbTimestamp_()});}
function cancelIssue_(id){var note=findById('IssueNotes',id);if(!note)throw apiError('NOT_FOUND','Không tìm thấy phiếu xuất: '+id);if(String(note.status)!=='posted')throw apiError('INVALID_STATE','Chỉ phiếu đã xuất mới được huỷ.');var moves=query('StockMovements',function(m){return String(m.ref_doc)===String(id)&&String(m.type)==='issue';});moves.forEach(function(m){var b=findBalance_(m.sku,m.wh_id),wasReserved=String(m.note)==='reserved';saveBalance_(m.sku,m.wh_id,Number(b.qty_on_hand)+Number(m.qty),Number(b.qty_reserved)+(wasReserved?Number(m.qty):0));if(wasReserved)insert('StockReservations',{res_id:nextId('RES'),project_id:m.project_id,sku:m.sku,wh_id:m.wh_id,qty:Number(m.qty),status:'active'});movement_('adjust',{sku:m.sku,wh_id:m.wh_id,qty:Number(m.qty),project_id:m.project_id,ref_doc:id,note:'Đảo phiếu xuất '+id});var bom=query('BOM',function(x){return String(x.project_id)===String(m.project_id)&&String(x.sku)===String(m.sku);})[0];if(bom)update('BOM',bom.bom_id,{qty_issued:Math.max(0,Number(bom.qty_issued||0)-Number(m.qty)),qty_reserved:Number(bom.qty_reserved||0)+(wasReserved?Number(m.qty):0)});});query('ProjectCosts',function(c){return String(c.ref_type)==='issue'&&String(c.ref_id)===String(id);}).forEach(function(c){insert('ProjectCosts',{id:nextId('COST'),project_id:c.project_id,kind:c.kind,amount_vnd:-Number(c.amount_vnd),ref_type:'issue_cancel',ref_id:id,ts:getDbTimestamp_()});});update('IssueNotes',id,{status:'cancelled'});return findById('IssueNotes',id);}
