function registerBomCostActions_() {
  registerActionOnce_('bom.list', function (p) { requireRole(getAuthContext_(), ['director','manager','engineer','purchasing','warehouse']); return listBom_(p && p.project_id, p && p.search); }, false);
  registerActionOnce_('bom.add_line', function (p) { requireRole(getAuthContext_(), ['manager','engineer']); return addBomLine_(p); }, true);
  registerActionOnce_('bom.update_line', function (p) { requireRole(getAuthContext_(), ['manager','engineer']); return updateBomLine_(p && p.bom_id, p && p.patch); }, true);
  registerActionOnce_('bom.delete_line', function (p) { requireRole(getAuthContext_(), ['manager','engineer']); return deleteBomLine_(p && p.bom_id); }, true);
  registerActionOnce_('bom.import_preview', function (p) { requireRole(getAuthContext_(), ['manager','engineer']); return previewBomImport_(p && p.rows, p && p.duplicate_mode); }, false);
  registerActionOnce_('bom.import_commit', function (p) { requireRole(getAuthContext_(), ['manager','engineer']); return commitBomImport_(p && p.project_id, p && p.rows, p && p.duplicate_mode); }, true);
  registerActionOnce_('project.cost', function (p) { requireRole(getAuthContext_(), ['director','manager','engineer','accountant']); return projectCost_(p && p.project_id); }, false);
}
function listBom_(projectId, search) { if (!findById('Projects', projectId)) throw apiError('NOT_FOUND', 'Không tìm thấy dự án: ' + projectId); var t=String(search||'').toLowerCase(); return query('BOM',function(r){return String(r.project_id)===String(projectId)&&( !t || [r.sku,r.note].join(' ').toLowerCase().indexOf(t)>=0);}).map(shapeBomLine_); }
function shapeBomLine_(r){var x=copyDbObject_(r),required=Number(r.qty_required||0),reserved=Number(r.qty_reserved||0),ordered=Number(r.qty_ordered||0),issued=Number(r.qty_issued||0);x.qty_short=Math.max(0,required-reserved-ordered-issued);x.state=issued>=required?'issued':x.qty_short>0?'short':ordered>0?'ordered':'reserved';return x;}
function normalizeBom_(p,isPatch){if(!p||Object.prototype.toString.call(p)!=='[object Object]')throw apiError('VALIDATION','Dữ liệu BOM phải là object.');var x={};MINI_ERP_SCHEMA.BOM.forEach(function(f){if(Object.prototype.hasOwnProperty.call(p,f)&&!(isPatch&&f==='bom_id'))x[f]=String(p[f]==null?'':p[f]).trim();});if(!isPatch&&(!x.project_id||!x.sku||!x.qty_required||!x.need_date))throw apiError('VALIDATION','Dự án, SKU, số lượng và ngày cần không được trống.');if(x.sku&&!findById('Items',x.sku))throw apiError('NOT_FOUND','SKU chưa có trong danh mục: '+x.sku,'sku');if(x.need_date&&!/^\d{4}-\d{2}-\d{2}$/.test(x.need_date))throw apiError('VALIDATION','Ngày cần phải theo YYYY-MM-DD.','need_date');['qty_required','qty_reserved','qty_ordered','qty_issued'].forEach(function(f){if(x[f]!==undefined&&x[f]!==''&&(!(Number(x[f])>=0)||(f==='qty_required'&&!(Number(x[f])>0))))throw apiError('VALIDATION',f+' không hợp lệ.',f);});return x;}
function assertBomInvariant_(row){if(Number(row.qty_reserved||0)+Number(row.qty_ordered||0)+Number(row.qty_issued||0)>Number(row.qty_required||0))throw apiError('VALIDATION','Tổng đã giữ chỗ, đã đặt và đã xuất không được vượt số lượng yêu cầu.','qty_required');}
function addBomLine_(p){if(!findById('Projects',p&&p.project_id))throw apiError('NOT_FOUND','Không tìm thấy dự án: '+(p&&p.project_id));var x=normalizeBom_(p,false);x.bom_id=x.bom_id||nextId('BOM');x.qty_reserved=x.qty_reserved||0;x.qty_ordered=x.qty_ordered||0;x.qty_issued=x.qty_issued||0;assertBomInvariant_(x);return shapeBomLine_(insert('BOM',x));}
function updateBomLine_(id,patch){var old=findById('BOM',id);if(!old)throw apiError('NOT_FOUND','Không tìm thấy dòng BOM: '+id);var x=normalizeBom_(patch,true),merged=copyDbObject_(old);Object.keys(x).forEach(function(k){merged[k]=x[k];});assertBomInvariant_(merged);return shapeBomLine_(update('BOM',id,x));}
function deleteBomLine_(id){var row=findById('BOM',id);if(!row)throw apiError('NOT_FOUND','Không tìm thấy dòng BOM: '+id);if(Number(row.qty_reserved||0)||Number(row.qty_ordered||0)||Number(row.qty_issued||0))throw apiError('CONFLICT','Không thể xoá dòng BOM đã phát sinh giữ chỗ, đặt mua hoặc xuất kho.');return softDelete('BOM',id);}
function previewBomImport_(rows,mode){if(!Array.isArray(rows)||!rows.length)throw apiError('VALIDATION','Chưa có dòng BOM.','rows');if(rows.length>500)throw apiError('VALIDATION','Mỗi lần nhập tối đa 500 dòng.','rows');mode=mode==='skip'?'skip':'sum';var grouped={},valid=[],errors=[];rows.forEach(function(r,i){try{var x=normalizeBom_({project_id:'PREVIEW',sku:r.sku,qty_required:r.qty_required,need_date:r.need_date,note:r.note||''},false);delete x.project_id;var key=x.sku+'|'+x.need_date;if(grouped[key]!==undefined){if(mode==='sum')valid[grouped[key]].qty_required=String(Number(valid[grouped[key]].qty_required)+Number(x.qty_required));}else{grouped[key]=valid.length;valid.push(x);}}catch(e){errors.push({row:i+2,field:e.field||'',message:e.message});}});return{valid_rows:valid,errors:errors,total:rows.length,duplicate_mode:mode};}
function commitBomImport_(projectId,rows,mode){if(!findById('Projects',projectId))throw apiError('NOT_FOUND','Không tìm thấy dự án: '+projectId);var preview=previewBomImport_(rows,mode);if(preview.errors.length)throw apiError('VALIDATION','Dữ liệu BOM còn lỗi.','rows');var values=preview.valid_rows.map(function(r){return{bom_id:nextId('BOM'),project_id:projectId,sku:r.sku,qty_required:r.qty_required,need_date:r.need_date,qty_reserved:0,qty_ordered:0,qty_issued:0,note:r.note||''};});return{created:insertMany('BOM',values).length,total:preview.total};}
function projectCost_(projectId){var p=findById('Projects',projectId);if(!p)throw apiError('NOT_FOUND','Không tìm thấy dự án: '+projectId);var totals={material:0,ot:0,trip:0,other:0};query('ProjectCosts',function(r){return String(r.project_id)===String(projectId);}).forEach(function(r){if(Object.prototype.hasOwnProperty.call(totals,String(r.kind)))totals[String(r.kind)]+=Number(r.amount_vnd||0);});var prices={};readAll('Items').forEach(function(i){prices[String(i.sku)]=Number(i.avg_cost_vnd||0);});var committed=query('BOM',function(r){return String(r.project_id)===String(projectId);}).reduce(function(s,r){return s+(Number(r.qty_reserved||0)+Number(r.qty_ordered||0))*Number(prices[String(r.sku)]||0);},0),actual=totals.material+totals.ot+totals.trip+totals.other;return{material:totals.material,ot:totals.ot,trip:totals.trip,other:totals.other,actual:actual,committed:committed,budget:Number(p.budget_vnd||0),gross_margin:Number(p.contract_value_vnd||0)-actual};}
