var MINI_ERP_PROJECT_STATUSES = ['draft','active','on_hold','done','cancelled'];
function registerProjectActions_() {
  registerActionOnce_('project.list', function () { var ctx=getAuthContext_(); requireRole(ctx, ['director','manager','engineer','purchasing','warehouse','accountant','employee']); return listProjects_(ctx); }, false);
  registerActionOnce_('project.get', function (p) { var ctx=getAuthContext_(); requireRole(ctx,['director','manager','engineer','purchasing','warehouse','accountant','employee']); var project=requireProjectAccess(ctx,p&&p.project_id); return projectDetail_(project); }, false);
  registerActionOnce_('project.create', function (p) { requireRole(getAuthContext_(), ['manager','engineer']); return createProject_(p); }, true);
  registerActionOnce_('project.update', function (p) { requireRole(getAuthContext_(), ['manager','engineer']); return updateProject_(p&&p.project_id,p&&p.patch); }, true);
  registerActionOnce_('project.set_status', function (p) { requireRole(getAuthContext_(), ['manager']); return setProjectStatus_(p&&p.project_id,p&&p.status); }, true);
  registerActionOnce_('payment.list', function (p) { requireRole(getAuthContext_(), ['director','manager','engineer','accountant']); return query('ProjectPayments',function(r){return String(r.project_id)===String(p&&p.project_id);}).sort(function(a,b){return Number(a.seq)-Number(b.seq);}); }, false);
  registerActionOnce_('payment.update_plan', function (p) { requireRole(getAuthContext_(), ['manager','accountant']); return updatePaymentPlan_(p&&p.project_id,p&&p.lines); }, true);
}
function listProjects_(ctx){var rows=readAll('Projects'),roles=[ctx.role].concat(ctx.extra_roles||[]);if(roles.indexOf('manager')>=0&&roles.indexOf('admin')<0)rows=rows.filter(function(p){return String(p.pm_emp_id)===String(ctx.emp_id);});if(roles.indexOf('employee')>=0&&roles.every(function(r){return['admin','director','manager','engineer','purchasing','warehouse','accountant'].indexOf(r)<0;})){var ids={};readAll('Tasks').forEach(function(t){if(String(t.assignee_emp_id)===String(ctx.emp_id))ids[String(t.project_id)]=true;});rows=rows.filter(function(p){return ids[String(p.project_id)];});}return rows.map(withProjectProgress_);}
function projectDetail_(project){var x=withProjectProgress_(project);x.payments=query('ProjectPayments',function(r){return String(r.project_id)===String(project.project_id);});x.bom=query('BOM',function(r){return String(r.project_id)===String(project.project_id);});x.tasks=query('Tasks',function(r){return String(r.project_id)===String(project.project_id);});return x;}
function withProjectProgress_(p){var x=copyDbObject_(p),tasks=query('Tasks',function(t){return String(t.project_id)===String(p.project_id);}),weights={wait:0,doing:.5,qc:.9,done:1};x.progress_pct=tasks.length?Math.round(tasks.reduce(function(s,t){return s+(weights[String(t.status)]||0);},0)/tasks.length*100):0;return x;}
function normalizeProject_(p,isPatch){if(!p||Object.prototype.toString.call(p)!=='[object Object]')throw apiError('VALIDATION','Dữ liệu dự án phải là object.');var x={};MINI_ERP_SCHEMA.Projects.forEach(function(f){if(Object.prototype.hasOwnProperty.call(p,f)&&!(isPatch&&f==='project_id'))x[f]=String(p[f]==null?'':p[f]).trim();});if(!isPatch&&(!x.name||!x.cust_id||!x.contract_value_vnd||!x.start_date||!x.due_date||!x.pm_emp_id))throw apiError('VALIDATION','Thiếu trường bắt buộc của dự án.');if(x.start_date&&x.due_date&&x.due_date<x.start_date)throw apiError('VALIDATION','Ngày kết thúc phải từ ngày bắt đầu trở đi.','due_date');if(x.contract_value_vnd!==undefined&&(!(Number(x.contract_value_vnd)>0)))throw apiError('VALIDATION','Giá trị hợp đồng phải lớn hơn 0.','contract_value_vnd');if(x.status&&MINI_ERP_PROJECT_STATUSES.indexOf(x.status)<0)throw apiError('VALIDATION','Trạng thái dự án không hợp lệ.','status');return x;}
function createProject_(p){var x=normalizeProject_(p,false);if(!findById('Customers',x.cust_id))throw apiError('NOT_FOUND','Không tìm thấy khách hàng: '+x.cust_id,'cust_id');if(!findById('Employees',x.pm_emp_id))throw apiError('NOT_FOUND','Không tìm thấy QLDA: '+x.pm_emp_id,'pm_emp_id');x.project_id=nextId('DA');x.status=x.status||'draft';var project=insert('Projects',x),v=Number(x.contract_value_vnd),names=['Tạm ứng','Giao hàng','Nghiệm thu'],perc=[30,50,20];insertMany('ProjectPayments',perc.map(function(pc,i){return{pay_id:x.project_id+'-PAY-'+(i+1),project_id:x.project_id,seq:i+1,name:names[i],percent:pc,amount_vnd:Math.round(v*pc/100),due_date:'',status:'pending'};}));return projectDetail_(project);}
function updateProject_(id,patch){if(!findById('Projects',id))throw apiError('NOT_FOUND','Không tìm thấy dự án: '+id);return withProjectProgress_(update('Projects',id,normalizeProject_(patch,true)));}
function setProjectStatus_(id,status){if(MINI_ERP_PROJECT_STATUSES.indexOf(String(status))<0)throw apiError('VALIDATION','Trạng thái dự án không hợp lệ.','status');return updateProject_(id,{status:status});}
function updatePaymentPlan_(projectId,lines){if(!findById('Projects',projectId))throw apiError('NOT_FOUND','Không tìm thấy dự án: '+projectId);if(!Array.isArray(lines)||!lines.length)throw apiError('VALIDATION','Kế hoạch thanh toán không được trống.','lines');var total=lines.reduce(function(s,l){return s+Number(l.percent||0);},0);if(Math.abs(total-100)>.0001)throw apiError('VALIDATION','Tổng tỷ lệ thanh toán phải bằng 100%.','percent');var project=findById('Projects',projectId),current=query('ProjectPayments',function(r){return String(r.project_id)===String(projectId);});lines.forEach(function(l,i){var old=current.filter(function(r){return String(r.pay_id)===String(l.pay_id);})[0];if(!old)throw apiError('NOT_FOUND','Không tìm thấy đợt thanh toán: '+l.pay_id);update('ProjectPayments',l.pay_id,{seq:i+1,name:String(l.name||old.name),percent:Number(l.percent),amount_vnd:Math.round(Number(project.contract_value_vnd)*Number(l.percent)/100),due_date:String(l.due_date||'')});});return query('ProjectPayments',function(r){return String(r.project_id)===String(projectId);});}
